### ISSUE TITLE
Cant run from source, appimage not available?

### ISSUE THREAD

**Issue by PlexSheep** [marcelloti/gpu-fan-control#2]
I have a Nvidia GTX 750 Ti that hat issues with its fan, (the RPM goes down to 0 often, then vroom RPM goes into high percentages, this loops every couple seconds.) Maybe this tool could help?

Here is the error output of ``npm run electron-serve``
```$ npm run electron-serve

> gpu-fan-control@0.1.0 electron-serve
> npm run electron:serve


> gpu-fan-control@0.1.0 electron:serve
> vue-cli-service electron:serve

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
 INFO  Starting development server...
10% building 2/5 modules 3 active ...rol/node_modules/eslint-loader/index.js??ref--13-0!/home/plex/Documents/code/gpu-fan-control/src/main.jsError: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/plex/Documents/code/gpu-fan-control/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/plex/Documents/code/gpu-fan-control/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/plex/Documents/code/gpu-fan-control/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/plex/Documents/code/gpu-fan-control/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/plex/Documents/code/gpu-fan-control/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/plex/Documents/code/gpu-fan-control/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/plex/Documents/code/gpu-fan-control/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/plex/Documents/code/gpu-fan-control/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/plex/Documents/code/gpu-fan-control/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/home/plex/Documents/code/gpu-fan-control/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/home/plex/Documents/code/gpu-fan-control/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/plex/Documents/code/gpu-fan-control/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/plex/Documents/code/gpu-fan-control/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/plex/Documents/code/gpu-fan-control/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/plex/Documents/code/gpu-fan-control/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/plex/Documents/code/gpu-fan-control/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/plex/Documents/code/gpu-fan-control/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/plex/Documents/code/gpu-fan-control/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/plex/Documents/code/gpu-fan-control/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/plex/Documents/code/gpu-fan-control/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/plex/Documents/code/gpu-fan-control/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/plex/Documents/code/gpu-fan-control/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/plex/Documents/code/gpu-fan-control/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/plex/Documents/code/gpu-fan-control/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /home/plex/Documents/code/gpu-fan-control/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.0
```

Not gonna lie, this project seems pretty dead, but it would be cool if not so.

**Comment by marcelloti** [comment]
Hi PlexSheep. I'm have updated the libs in package.json and also added an AppImage in root. Let me known if this helped you. :)

**Comment by PlexSheep** [comment]
It runs and works with the appimage. Thank you, Issue closed.

Unfortunately i have a dual GPU setup, and the GPU i want to control that way is GPU1 not GPU0 and the tool doesnt do multi GPU (which I didn't expect, but it was worth a try. Not even GreenWithEnvy has that)

Thanks for the quick response.
